parameters:
- name: SERVICE_CONNECTION
  type: string
  default: pypi

jobs:
- job: PyPI_Deploy
  pool:
    vmImage: 'ubuntu-20.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
  - script: |
      python3 --version
      python3 -m pip install -U pip
      pip3 install setuptools wheel twine
      python3 setup.py bdist_wheel
    displayName: 'Install Packages'
  - task: TwineAuthenticate@1
    displayName: 'Twine Authenticate'
    inputs:
      pythonUploadServiceConnection: ${{ parameters.SERVICE_CONNECTION }}
  - script: python3 -m twine upload --config-file $(PYPIRC_PATH) dist/*.whl
    displayName: 'Twine Upload'
