parameters:
  - name: REPO_NAME
    type: string
  # The following parameters have defaults because this template could be used by repos directly
  - name: TIMEOUT
    type: number
    default: 10
  - name: IGNORE_STYLE
    type: boolean
    default: false
  - name: ISORT
    type: boolean
    default: false
  - name: PYLINT
    type: boolean
    default: false
  - name: CLANG_FORMAT
    type: boolean
    default: false
  - name: FPRETTIFY
    type: boolean
    default: false

jobs:
  - job: flake8
    pool:
      vmImage: "ubuntu-20.04"
    timeoutInMinutes: ${{ parameters.TIMEOUT }}
    continueOnError: ${{ parameters.IGNORE_STYLE }}
    strategy:
      matrix:
        "py38":
          PYTHON_VERSION: "3.8"
        "py39":
          PYTHON_VERSION: "3.9"
    steps:
      - checkout: self
      - checkout: azure_template
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(PYTHON_VERSION)
      - script: |
          cd ${{ parameters.REPO_NAME }}
          pip install wheel
          pip install -r ../.github/flake8-requirements.txt

          if [[ -f ".flake8" ]]; then
            export FL8=.flake8-project
            mv .flake8 $FL8; # rename the file from code repo; should have higher precedence in merge
          fi

          cp ../.github/.flake8 .

          if [[ -f "$FL8" ]]; then
              flake8 . --append-config $FL8 --count --show-source --statistics;
          else
              flake8 . --count --show-source --statistics;
          fi

  - job: black
    pool:
      vmImage: "ubuntu-20.04"
    timeoutInMinutes: ${{ parameters.TIMEOUT }}
    continueOnError: ${{ parameters.IGNORE_STYLE }}
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.9"
      - script: |
          pip install wheel
          pip install black==22.3.0
          black . --check --diff -l 120 --target-version py38 --target-version py39

  - job: isort
    pool:
      vmImage: "ubuntu-20.04"
    timeoutInMinutes: ${{ parameters.TIMEOUT }}
    condition: ${{ parameters.ISORT }}
    steps:
      - checkout: self
      - checkout: azure_template
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.9"
      - script: |
          cd ${{ parameters.REPO_NAME }}

          # copy over the isort config file
          if [[ ! -f ".isort.cfg" ]]; then
            cp ../.github/.isort.cfg .
          fi

          pip install wheel
          pip install isort
          isort . -c

  - job: pylint
    pool:
      vmImage: "ubuntu-20.04"
    timeoutInMinutes: ${{ parameters.TIMEOUT }}
    condition: ${{ parameters.PYLINT }}
    steps:
      - checkout: self
      - checkout: azure_template
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.9"
      - script: |
          cd ${{ parameters.REPO_NAME }}

          # copy over the pylint config file
          cp ../.github/.pylintrc .

          pip install pylint
          find . -type f -name "*.py" -not -path "*/doc/*" | xargs pylint

  - job: clang_format
    pool:
      vmImage: "ubuntu-20.04"
    timeoutInMinutes: ${{ parameters.TIMEOUT }}
    condition: ${{ parameters.CLANG_FORMAT }}
    steps:
      - checkout: self
      - checkout: azure_template
      - script: |
          # Install prerequisites
          sudo apt-get install clang-format-10 -y

          cd ${{ parameters.REPO_NAME }}

          # if no local file is found in the repository, copy over the global .clang-format config file
          if [[ ! -f ".clang-format" ]]; then
            cp ../.github/.clang-format . || exit 1
          fi

          find . -iname '*.h' -o -iname '*.hpp' -o -iname '*.c' -o -iname '*.cpp' | xargs clang-format --verbose --dry-run --Werror -style=file

  - job: fprettify
    pool:
      vmImage: "ubuntu-20.04"
    timeoutInMinutes: ${{ parameters.TIMEOUT }}
    condition: ${{ parameters.FPRETTIFY }}
    steps:
      - checkout: self
      - checkout: azure_template
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "3.9"
      - script: |
          cd ${{ parameters.REPO_NAME }}

          # If there is no local config file, copy over the global config file
          if [[ ! -f ".fprettify.rc" ]]; then
            cp ../.github/.fprettify.rc .
          fi

          # Install fprettify
          pip install fprettify==0.3.7

          # Run fprettify on non-differentiated Fortran 90 source files
          find . -type f -iname '*.f90' ! -iname '*_b.f90' ! -iname '*_d.f90' -print0 | while read -d $'\0' file
          do
            echo Checking $file
            fprettify $file

            # Check if this file changed and print a message if it did
            git diff --summary --exit-code $file
            if [ $? -ne 0 ]; then
              echo $file needs to be formatted
            fi
          done

          # Exit with an error if any of the tracked files changed
          git diff --summary --exit-code
