parameters:
  - name: REPO_NAME
    type: string
  - name: IGNORE_STYLE
    type: boolean
    default: false
  - name: IGNORE_ISORT
    type: boolean
    default: true
  - name: COMPLEX
    type: boolean
    default: false
  - name: GCC_CONFIG
    type: string
    default: None
  - name: INTEL_CONFIG
    type: string
    default: None
  - name: BUILD_REAL
    type: string
    default: .github/build_real.sh
  - name: TEST_REAL
    type: string
    default: .github/test_real.sh
  - name: BUILD_COMPLEX
    type: string
    default: .github/build_complex.sh
  - name: TEST_COMPLEX
    type: string
    default: .github/test_complex.sh
  - name: IMAGE
    type: string
    default: public
  - name: SKIP_TESTS
    type: boolean
    default: false
  - name: TIMEOUT
    type: number
    default: 0

stages:
  - stage: Test_Real
    dependsOn: []
    displayName: Test Real
    condition: not(${{ parameters.SKIP_TESTS }})
    jobs:
      - template: azure_build.yaml
        parameters:
          REPO_NAME: ${{ parameters.REPO_NAME }}
          GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
          INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
          BUILD: ${{ parameters.BUILD_REAL }}
          TEST: ${{ parameters.TEST_REAL }}
          IMAGE: ${{ parameters.IMAGE }}
          TIMEOUT: ${{ parameters.TIMEOUT }}

  - stage: Test_Complex
    dependsOn: []
    displayName: Test Complex
    condition: and(eq(${{ parameters.COMPLEX }}, true), not(${{ parameters.SKIP_TESTS }}))
    jobs:
      - template: azure_build.yaml
        parameters:
          REPO_NAME: ${{ parameters.REPO_NAME }}
          GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
          INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
          BUILD: ${{ parameters.BUILD_COMPLEX }}
          TEST: ${{ parameters.TEST_COMPLEX }}
          IMAGE: ${{ parameters.IMAGE }}
          TIMEOUT: ${{ parameters.TIMEOUT }}

  - stage: Style
    dependsOn: []
    displayName: Style
    condition: not(${{ parameters.SKIP_TESTS }})
    jobs:
      - template: azure_style.yaml
        parameters:
          REPO_NAME: ${{ parameters.REPO_NAME }}
          IGNORE_STYLE: ${{ parameters.IGNORE_STYLE }}
          IGNORE_ISORT: ${{ parameters.IGNORE_ISORT }}
