parameters:
  - name: REPO_NAME
    type: string
  # Build and test
  - name: COMPLEX
    type: boolean
    default: false
  - name: TIMEOUT_BUILD
    type: number
    default: 120
  - name: GCC_CONFIG
    type: string
    default: None
  - name: INTEL_CONFIG
    type: string
    default: None
  - name: BUILD_REAL
    type: string
    default: .github/build_real.sh
  - name: TEST_REAL
    type: string
    default: .github/test_real.sh
  - name: BUILD_COMPLEX
    type: string
    default: .github/build_complex.sh
  - name: TEST_COMPLEX
    type: string
    default: .github/test_complex.sh
  - name: IMAGE
    type: string
    default: public
  - name: COVERAGE
    type: boolean
    default: false
  - name: C_COVERAGE
    type: boolean
    default: false
  # Style checks
  - name: TIMEOUT_STYLE
    type: number
    default: 10
  - name: IGNORE_STYLE
    type: boolean
    default: false
  - name: ISORT
    type: boolean
    default: false
  - name: PYLINT
    type: boolean
    default: false
  - name: CLANG_FORMAT
    type: boolean
    default: false
  - name: FPRETTIFY
    type: boolean
    default: false
  # Tapenade
  - name: TAPENADE
    type: boolean
    default: false
  - name: TIMEOUT_TAPENADE
    type: number
    default: 10
  - name: TAPENADE_SCRIPT
    type: string
    default: .github/build_tapenade.sh
  - name: TAPENADE_VERSION
    type: string
    default: 3.10


stages:
  - stage: Test_Real
    dependsOn: []
    displayName: Real Test
    jobs:
      - template: azure_build.yaml
        parameters:
          REPO_NAME: ${{ parameters.REPO_NAME }}
          TIMEOUT: ${{ parameters.TIMEOUT_BUILD }}
          GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
          INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
          BUILD: ${{ parameters.BUILD_REAL }}
          TEST: ${{ parameters.TEST_REAL }}
          IMAGE: ${{ parameters.IMAGE }}
          COVERAGE: ${{ parameters.COVERAGE }}
          C_COVERAGE: ${{ parameters.C_COVERAGE }}

  - stage: Test_Complex
    dependsOn: []
    displayName: Complex Test
    condition: ${{ parameters.COMPLEX }}
    jobs:
      - template: azure_build.yaml
        parameters:
          REPO_NAME: ${{ parameters.REPO_NAME }}
          TIMEOUT: ${{ parameters.TIMEOUT_BUILD }}
          GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
          INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
          BUILD: ${{ parameters.BUILD_COMPLEX }}
          TEST: ${{ parameters.TEST_COMPLEX }}
          IMAGE: ${{ parameters.IMAGE }}
          COVERAGE: ${{ parameters.COVERAGE }}
          C_COVERAGE: ${{ parameters.C_COVERAGE }}

  - stage: Style
    dependsOn: []
    displayName: Style Checks
    jobs:
      - template: azure_style.yaml
        parameters:
          REPO_NAME: ${{ parameters.REPO_NAME }}
          TIMEOUT: ${{ parameters.TIMEOUT_STYLE }}
          IGNORE_STYLE: ${{ parameters.IGNORE_STYLE }}
          ISORT: ${{ parameters.ISORT }}
          PYLINT: ${{ parameters.PYLINT }}
          CLANG_FORMAT: ${{ parameters.CLANG_FORMAT }}
          FPRETTIFY: ${{ parameters.FPRETTIFY }}

  - stage: Tapenade
    dependsOn: []
    displayName: Tapenade Checks
    condition: ${{ parameters.TAPENADE }}
    jobs:
      - template: azure_tapenade.yaml
        parameters:
          REPO_NAME: ${{ parameters.REPO_NAME }}
          TIMEOUT: ${{ parameters.TIMEOUT_TAPENADE }}
          TAPENADE_SCRIPT: ${{ parameters.TAPENADE_SCRIPT }}
          TAPENADE_VERSION: ${{ parameters.TAPENADE_VERSION }}
