version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - "maintenance"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
