exclude: ^.*\.(cgns|CGNS)$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: debug-statements
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.10
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix, --exit-non-zero-on-fix ]
    # Run the formatter.
    - id: ruff-format
