# --- The Linux Group ---
[bbots_linux]
bbot1
bbot2
bbot3
bbot4
bbot5
bbot6
bbot8
bbot9

# --- The Mac Group ---
[bbots_mac]
bbot7

# --- The Parent Group (so you can still target 'all') ---
[bbots:children]
bbots_linux
bbots_mac