on:
  workflow_call:
    inputs:
      black_version:
        required: false
        type: string
        default: "23.1.0"

jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --diff -l 120 --target-version py39 --target-version py311"
          version: ${{ inputs.black_version }}
