on:
  workflow_call:
    inputs:
      black:
        required: false
        type: boolean
        default: true
      clang_format:
        required: false
        type: boolean
        default: false

jobs:
  black:
    if: ${{ inputs.black }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --diff -l 120 --target-version py38 --target-version py39"
          version: "22.1.0"

  clang_format:
    if: ${{ inputs.clang_format }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install clang-format-10 -y
      - name: Run clang_format
        run: |
          bash ./.github/clang_format.sh
