on:
  workflow_call:
    inputs:
      black:
        required: false
        type: boolean
        default: true
      black_version:
        required: false
        type: string
        default: "22.3.0"
      clang_format:
        required: false
        type: boolean
        default: false
      isort:
        required: false
        type: boolean
        default: false

jobs:
  black:
    if: ${{ inputs.black }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --diff -l 120 --target-version py38 --target-version py39"
          version: ${{ inputs.black_version }}

  clang_format:
    if: ${{ inputs.clang_format }}
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install clang-format-10 -y
      - name: Run clang_format
        run: |
          bash ./.github/clang_format.sh

  isort:
    if: ${{ inputs.isort }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Get isort config file
        run: |
          # copy over the isort config file
          if [[ ! -f ".isort.cfg" ]]; then
            wget https://raw.githubusercontent.com/mdolab/.github/main/.isort.cfg
          fi
      - uses: isort/isort-action@master
