on:
  workflow_call:

jobs:
  mypy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install wheel
          pip install mypy
      - name: Mypy check
        run: |
          mypy --any-exprs-report mypy-output .
          cat mypy-output/any-exprs.txt
